type: yolov5
name: yolov5s-onnx-r20250726
display_name: YOLOv5s ONNX
model_path: C:/Users/Administrator/Desktop/exp/weights/best.onnx
input_width: 640
input_height: 640
stride: 32
nms_threshold: 0.45
confidence_threshold: 0.45
classes:
- body
version: '1.0'
preprocess:
  scale: 0.00392156862745098
  swap_rgb: true
